import {
  boolean,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  unique,
  varchar,
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

// ---------------------------------------------------------------------------
// Auth tables — generated by better-auth, do NOT modify column names
// ---------------------------------------------------------------------------

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('emailVerified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('createdAt').notNull().defaultNow(),
  updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expiresAt').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('createdAt').notNull(),
  updatedAt: timestamp('updatedAt').notNull(),
  ipAddress: text('ipAddress'),
  userAgent: text('userAgent'),
  userId: text('userId').notNull(),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('accountId').notNull(),
  providerId: text('providerId').notNull(),
  userId: text('userId').notNull(),
  accessToken: text('accessToken'),
  refreshToken: text('refreshToken'),
  idToken: text('idToken'),
  accessTokenExpiresAt: timestamp('accessTokenExpiresAt'),
  refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'),
  scope: text('scope'),
  password: text('password'),
  issuer: text('issuer'),
  createdAt: timestamp('createdAt').notNull(),
  updatedAt: timestamp('updatedAt').notNull(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expiresAt').notNull(),
  createdAt: timestamp('createdAt'),
  updatedAt: timestamp('updatedAt'),
})

// ---------------------------------------------------------------------------
// Subject — e.g. Mathematics, Physics, Chemistry, Biology, English
// ---------------------------------------------------------------------------

export const subject = pgTable('subject', {
  id: serial('id').primaryKey(),
  // URL-safe slug, e.g. "mathematics"
  slug: varchar('slug', { length: 80 }).notNull().unique(),
  name: varchar('name', { length: 120 }).notNull(),
  // Lucide icon name used in the UI, e.g. "Calculator"
  iconName: varchar('icon_name', { length: 60 }).notNull().default('BookOpen'),
  description: text('description'),
  // Display order in subject lists
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Exam — one row per distinct exam sitting
// e.g. "EUEE 2005", "EUEE 2009"
// Designed to be extensible: exam_type can accommodate future types
// ---------------------------------------------------------------------------

export const exam = pgTable('exam', {
  id: serial('id').primaryKey(),
  // "euee" to start; can add "grade10_national", etc. later
  examType: varchar('exam_type', { length: 60 }).notNull().default('euee'),
  year: integer('year').notNull(),
  // Human-readable label, e.g. "EUEE 2005"
  label: varchar('label', { length: 120 }).notNull(),
  // Optional: grade context for future multi-grade support
  gradeLevel: integer('grade_level'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Topic — fine-grained categorisation within a subject
// e.g. "Quadratic Equations" under Mathematics
// ---------------------------------------------------------------------------

export const topic = pgTable('topic', {
  id: serial('id').primaryKey(),
  subjectId: integer('subject_id')
    .notNull()
    .references(() => subject.id),
  name: varchar('name', { length: 150 }).notNull(),
  slug: varchar('slug', { length: 120 }).notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Question — one row per exam question
// ---------------------------------------------------------------------------

export const question = pgTable('question', {
  id: serial('id').primaryKey(),
  examId: integer('exam_id')
    .notNull()
    .references(() => exam.id),
  subjectId: integer('subject_id')
    .notNull()
    .references(() => subject.id),
  topicId: integer('topic_id').references(() => topic.id),
  // Question number as it appears in the original exam
  orderIndex: integer('order_index').notNull().default(1),
  // Full question text (may contain LaTeX-style notation)
  body: text('body').notNull(),
  // Explanation shown after the student answers — sourced from PDF answer keys
  explanation: text('explanation'),
  // "easy" | "medium" | "hard" — can be null until manually tagged
  difficulty: varchar('difficulty', { length: 20 }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Option — answer choices for a question (typically A–D)
// ---------------------------------------------------------------------------

export const option = pgTable('option', {
  id: serial('id').primaryKey(),
  questionId: integer('question_id')
    .notNull()
    .references(() => question.id, { onDelete: 'cascade' }),
  // "A" | "B" | "C" | "D"
  label: varchar('label', { length: 5 }).notNull(),
  body: text('body').notNull(),
  isCorrect: boolean('is_correct').notNull().default(false),
})

// ---------------------------------------------------------------------------
// PracticeSession — one row each time a user starts a practice run
// ---------------------------------------------------------------------------

export const practiceSession = pgTable('practice_session', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id),
  examId: integer('exam_id')
    .notNull()
    .references(() => exam.id),
  subjectId: integer('subject_id')
    .notNull()
    .references(() => subject.id),
  startedAt: timestamp('started_at').notNull().defaultNow(),
  completedAt: timestamp('completed_at'),
  // Cached totals — updated as answers are submitted
  totalQuestions: integer('total_questions').notNull().default(0),
  correctCount: integer('correct_count').notNull().default(0),
})

// ---------------------------------------------------------------------------
// SessionAnswer — one row per question answered in a practice session
// ---------------------------------------------------------------------------

export const sessionAnswer = pgTable('session_answer', {
  id: serial('id').primaryKey(),
  sessionId: integer('session_id')
    .notNull()
    .references(() => practiceSession.id, { onDelete: 'cascade' }),
  questionId: integer('question_id')
    .notNull()
    .references(() => question.id),
  selectedOptionId: integer('selected_option_id').references(() => option.id),
  isCorrect: boolean('is_correct').notNull().default(false),
  // How long the student spent on this question in milliseconds
  timeSpentMs: integer('time_spent_ms'),
  answeredAt: timestamp('answered_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Bookmark — saved questions per user
// ---------------------------------------------------------------------------

export const bookmark = pgTable('bookmark', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id),
  questionId: integer('question_id')
    .notNull()
    .references(() => question.id),
  createdAt: timestamp('created_at').notNull().defaultNow(),
}, (t) => [
  unique('bookmark_user_id_question_id_unique').on(t.userId, t.questionId),
])

// ---------------------------------------------------------------------------
// Relations — for Drizzle relational query API
// ---------------------------------------------------------------------------

export const subjectRelations = relations(subject, ({ many }) => ({
  topics: many(topic),
  questions: many(question),
  practiceSessions: many(practiceSession),
}))

export const examRelations = relations(exam, ({ many }) => ({
  questions: many(question),
  practiceSessions: many(practiceSession),
}))

export const topicRelations = relations(topic, ({ one, many }) => ({
  subject: one(subject, { fields: [topic.subjectId], references: [subject.id] }),
  questions: many(question),
}))

export const questionRelations = relations(question, ({ one, many }) => ({
  exam: one(exam, { fields: [question.examId], references: [exam.id] }),
  subject: one(subject, { fields: [question.subjectId], references: [subject.id] }),
  topic: one(topic, { fields: [question.topicId], references: [topic.id] }),
  options: many(option),
  sessionAnswers: many(sessionAnswer),
  bookmarks: many(bookmark),
}))

export const optionRelations = relations(option, ({ one }) => ({
  question: one(question, { fields: [option.questionId], references: [question.id] }),
}))

export const practiceSessionRelations = relations(practiceSession, ({ one, many }) => ({
  user: one(user, { fields: [practiceSession.userId], references: [user.id] }),
  exam: one(exam, { fields: [practiceSession.examId], references: [exam.id] }),
  subject: one(subject, { fields: [practiceSession.subjectId], references: [subject.id] }),
  answers: many(sessionAnswer),
}))

export const sessionAnswerRelations = relations(sessionAnswer, ({ one }) => ({
  session: one(practiceSession, { fields: [sessionAnswer.sessionId], references: [practiceSession.id] }),
  question: one(question, { fields: [sessionAnswer.questionId], references: [question.id] }),
  selectedOption: one(option, { fields: [sessionAnswer.selectedOptionId], references: [option.id] }),
}))

export const bookmarkRelations = relations(bookmark, ({ one }) => ({
  user: one(user, { fields: [bookmark.userId], references: [user.id] }),
  question: one(question, { fields: [bookmark.questionId], references: [question.id] }),
}))

export const userRelations = relations(user, ({ many }) => ({
  practiceSessions: many(practiceSession),
  bookmarks: many(bookmark),
  groupMemberships: many(groupMembership),
  groupPosts: many(groupPost),
}))

// ---------------------------------------------------------------------------
// Study Group
// ---------------------------------------------------------------------------

export const studyGroup = pgTable('study_group', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 150 }).notNull(),
  description: text('description'),
  examId: integer('exam_id').references(() => exam.id, { onDelete: 'set null' }),
  ownerId: text('owner_id').notNull().references(() => user.id),
  privacy: varchar('privacy', { length: 10 }).notNull().default('public'),
  goal: text('goal'),
  inviteToken: varchar('invite_token', { length: 64 }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (t) => [
  unique('study_group_invite_token_unique').on(t.inviteToken),
])

export const studyGroupSubject = pgTable('study_group_subject', {
  id: serial('id').primaryKey(),
  groupId: integer('group_id').notNull().references(() => studyGroup.id, { onDelete: 'cascade' }),
  subjectId: integer('subject_id').notNull().references(() => subject.id, { onDelete: 'cascade' }),
}, (t) => [
  unique('study_group_subject_group_subject_unique').on(t.groupId, t.subjectId),
])

export const groupMembership = pgTable('group_membership', {
  id: serial('id').primaryKey(),
  groupId: integer('group_id').notNull().references(() => studyGroup.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  // 'owner' | 'admin' | 'member'
  role: varchar('role', { length: 10 }).notNull().default('member'),
  joinedAt: timestamp('joined_at').notNull().defaultNow(),
}, (t) => [
  unique('group_membership_group_user_unique').on(t.groupId, t.userId),
])

export const groupPost = pgTable('group_post', {
  id: serial('id').primaryKey(),
  groupId: integer('group_id').notNull().references(() => studyGroup.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  content: text('content').notNull(),
  questionId: integer('question_id').references(() => question.id, { onDelete: 'set null' }),
  isPinned: boolean('is_pinned').notNull().default(false),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const groupComment = pgTable('group_comment', {
  id: serial('id').primaryKey(),
  postId: integer('post_id').notNull().references(() => groupPost.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  content: text('content').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const groupChallenge = pgTable('group_challenge', {
  id: serial('id').primaryKey(),
  groupId: integer('group_id').notNull().references(() => studyGroup.id, { onDelete: 'cascade' }),
  title: varchar('title', { length: 200 }).notNull(),
  description: text('description'),
  subjectId: integer('subject_id').references(() => subject.id, { onDelete: 'set null' }),
  examId: integer('exam_id').references(() => exam.id, { onDelete: 'set null' }),
  questionCount: integer('question_count').notNull().default(10),
  timeLimitMins: integer('time_limit_mins').notNull().default(15),
  createdBy: text('created_by').notNull().references(() => user.id),
  startAt: timestamp('start_at').notNull(),
  endAt: timestamp('end_at').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

export const challengeQuestion = pgTable('challenge_question', {
  id: serial('id').primaryKey(),
  challengeId: integer('challenge_id').notNull().references(() => groupChallenge.id, { onDelete: 'cascade' }),
  questionId: integer('question_id').notNull().references(() => question.id, { onDelete: 'cascade' }),
  orderIndex: integer('order_index').notNull().default(1),
}, (t) => [
  unique('challenge_question_challenge_question_unique').on(t.challengeId, t.questionId),
])

export const challengeAttempt = pgTable('challenge_attempt', {
  id: serial('id').primaryKey(),
  challengeId: integer('challenge_id').notNull().references(() => groupChallenge.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  score: integer('score').notNull().default(0),
  total: integer('total').notNull().default(0),
  accuracy: integer('accuracy').notNull().default(0),
  timeTakenMs: integer('time_taken_ms'),
  completedAt: timestamp('completed_at'),
  startedAt: timestamp('started_at').notNull().defaultNow(),
}, (t) => [
  unique('challenge_attempt_challenge_user_unique').on(t.challengeId, t.userId),
])

export const challengeAnswer = pgTable('challenge_answer', {
  id: serial('id').primaryKey(),
  attemptId: integer('attempt_id').notNull().references(() => challengeAttempt.id, { onDelete: 'cascade' }),
  questionId: integer('question_id').notNull().references(() => question.id, { onDelete: 'cascade' }),
  selectedOptionId: integer('selected_option_id').references(() => option.id, { onDelete: 'set null' }),
  isCorrect: boolean('is_correct').notNull().default(false),
  answeredAt: timestamp('answered_at').notNull().defaultNow(),
})

export const contentReport = pgTable('content_report', {
  id: serial('id').primaryKey(),
  reporterId: text('reporter_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  postId: integer('post_id').references(() => groupPost.id, { onDelete: 'set null' }),
  commentId: integer('comment_id').references(() => groupComment.id, { onDelete: 'set null' }),
  reason: varchar('reason', { length: 50 }).notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Study Group Relations
// ---------------------------------------------------------------------------

export const studyGroupRelations = relations(studyGroup, ({ one, many }) => ({
  owner: one(user, { fields: [studyGroup.ownerId], references: [user.id] }),
  exam: one(exam, { fields: [studyGroup.examId], references: [exam.id] }),
  subjects: many(studyGroupSubject),
  memberships: many(groupMembership),
  posts: many(groupPost),
  challenges: many(groupChallenge),
}))

export const studyGroupSubjectRelations = relations(studyGroupSubject, ({ one }) => ({
  group: one(studyGroup, { fields: [studyGroupSubject.groupId], references: [studyGroup.id] }),
  subject: one(subject, { fields: [studyGroupSubject.subjectId], references: [subject.id] }),
}))

export const groupMembershipRelations = relations(groupMembership, ({ one }) => ({
  group: one(studyGroup, { fields: [groupMembership.groupId], references: [studyGroup.id] }),
  user: one(user, { fields: [groupMembership.userId], references: [user.id] }),
}))

export const groupPostRelations = relations(groupPost, ({ one, many }) => ({
  group: one(studyGroup, { fields: [groupPost.groupId], references: [studyGroup.id] }),
  user: one(user, { fields: [groupPost.userId], references: [user.id] }),
  question: one(question, { fields: [groupPost.questionId], references: [question.id] }),
  comments: many(groupComment),
}))

export const groupCommentRelations = relations(groupComment, ({ one }) => ({
  post: one(groupPost, { fields: [groupComment.postId], references: [groupPost.id] }),
  user: one(user, { fields: [groupComment.userId], references: [user.id] }),
}))

export const groupChallengeRelations = relations(groupChallenge, ({ one, many }) => ({
  group: one(studyGroup, { fields: [groupChallenge.groupId], references: [studyGroup.id] }),
  subject: one(subject, { fields: [groupChallenge.subjectId], references: [subject.id] }),
  exam: one(exam, { fields: [groupChallenge.examId], references: [exam.id] }),
  createdByUser: one(user, { fields: [groupChallenge.createdBy], references: [user.id] }),
  questions: many(challengeQuestion),
  attempts: many(challengeAttempt),
}))

export const challengeQuestionRelations = relations(challengeQuestion, ({ one }) => ({
  challenge: one(groupChallenge, { fields: [challengeQuestion.challengeId], references: [groupChallenge.id] }),
  question: one(question, { fields: [challengeQuestion.questionId], references: [question.id] }),
}))

export const challengeAttemptRelations = relations(challengeAttempt, ({ one, many }) => ({
  challenge: one(groupChallenge, { fields: [challengeAttempt.challengeId], references: [groupChallenge.id] }),
  user: one(user, { fields: [challengeAttempt.userId], references: [user.id] }),
  answers: many(challengeAnswer),
}))

export const challengeAnswerRelations = relations(challengeAnswer, ({ one }) => ({
  attempt: one(challengeAttempt, { fields: [challengeAnswer.attemptId], references: [challengeAttempt.id] }),
  question: one(question, { fields: [challengeAnswer.questionId], references: [question.id] }),
  selectedOption: one(option, { fields: [challengeAnswer.selectedOptionId], references: [option.id] }),
}))
