import {
  boolean,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  unique,
  varchar,
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

// ---------------------------------------------------------------------------
// Auth tables — generated by better-auth, do NOT modify column names
// ---------------------------------------------------------------------------

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('emailVerified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('createdAt').notNull().defaultNow(),
  updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expiresAt').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('createdAt').notNull(),
  updatedAt: timestamp('updatedAt').notNull(),
  ipAddress: text('ipAddress'),
  userAgent: text('userAgent'),
  userId: text('userId').notNull(),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('accountId').notNull(),
  providerId: text('providerId').notNull(),
  userId: text('userId').notNull(),
  accessToken: text('accessToken'),
  refreshToken: text('refreshToken'),
  idToken: text('idToken'),
  accessTokenExpiresAt: timestamp('accessTokenExpiresAt'),
  refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'),
  scope: text('scope'),
  password: text('password'),
  issuer: text('issuer'),
  createdAt: timestamp('createdAt').notNull(),
  updatedAt: timestamp('updatedAt').notNull(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expiresAt').notNull(),
  createdAt: timestamp('createdAt'),
  updatedAt: timestamp('updatedAt'),
})

// ---------------------------------------------------------------------------
// Subject — e.g. Mathematics, Physics, Chemistry, Biology, English
// ---------------------------------------------------------------------------

export const subject = pgTable('subject', {
  id: serial('id').primaryKey(),
  // URL-safe slug, e.g. "mathematics"
  slug: varchar('slug', { length: 80 }).notNull().unique(),
  name: varchar('name', { length: 120 }).notNull(),
  // Lucide icon name used in the UI, e.g. "Calculator"
  iconName: varchar('icon_name', { length: 60 }).notNull().default('BookOpen'),
  description: text('description'),
  // Display order in subject lists
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Exam — one row per distinct exam sitting
// e.g. "EUEE 2005", "EUEE 2009"
// Designed to be extensible: exam_type can accommodate future types
// ---------------------------------------------------------------------------

export const exam = pgTable('exam', {
  id: serial('id').primaryKey(),
  // "euee" to start; can add "grade10_national", etc. later
  examType: varchar('exam_type', { length: 60 }).notNull().default('euee'),
  year: integer('year').notNull(),
  // Human-readable label, e.g. "EUEE 2005"
  label: varchar('label', { length: 120 }).notNull(),
  // Optional: grade context for future multi-grade support
  gradeLevel: integer('grade_level'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Topic — fine-grained categorisation within a subject
// e.g. "Quadratic Equations" under Mathematics
// ---------------------------------------------------------------------------

export const topic = pgTable('topic', {
  id: serial('id').primaryKey(),
  subjectId: integer('subject_id')
    .notNull()
    .references(() => subject.id),
  name: varchar('name', { length: 150 }).notNull(),
  slug: varchar('slug', { length: 120 }).notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Question — one row per exam question
// ---------------------------------------------------------------------------

export const question = pgTable('question', {
  id: serial('id').primaryKey(),
  examId: integer('exam_id')
    .notNull()
    .references(() => exam.id),
  subjectId: integer('subject_id')
    .notNull()
    .references(() => subject.id),
  topicId: integer('topic_id').references(() => topic.id),
  // Question number as it appears in the original exam
  orderIndex: integer('order_index').notNull().default(1),
  // Full question text (may contain LaTeX-style notation)
  body: text('body').notNull(),
  // Explanation shown after the student answers — sourced from PDF answer keys
  explanation: text('explanation'),
  // "easy" | "medium" | "hard" — can be null until manually tagged
  difficulty: varchar('difficulty', { length: 20 }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Option — answer choices for a question (typically A–D)
// ---------------------------------------------------------------------------

export const option = pgTable('option', {
  id: serial('id').primaryKey(),
  questionId: integer('question_id')
    .notNull()
    .references(() => question.id, { onDelete: 'cascade' }),
  // "A" | "B" | "C" | "D"
  label: varchar('label', { length: 5 }).notNull(),
  body: text('body').notNull(),
  isCorrect: boolean('is_correct').notNull().default(false),
})

// ---------------------------------------------------------------------------
// PracticeSession — one row each time a user starts a practice run
// ---------------------------------------------------------------------------

export const practiceSession = pgTable('practice_session', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id),
  examId: integer('exam_id')
    .notNull()
    .references(() => exam.id),
  subjectId: integer('subject_id')
    .notNull()
    .references(() => subject.id),
  startedAt: timestamp('started_at').notNull().defaultNow(),
  completedAt: timestamp('completed_at'),
  // Cached totals — updated as answers are submitted
  totalQuestions: integer('total_questions').notNull().default(0),
  correctCount: integer('correct_count').notNull().default(0),
})

// ---------------------------------------------------------------------------
// SessionAnswer — one row per question answered in a practice session
// ---------------------------------------------------------------------------

export const sessionAnswer = pgTable('session_answer', {
  id: serial('id').primaryKey(),
  sessionId: integer('session_id')
    .notNull()
    .references(() => practiceSession.id, { onDelete: 'cascade' }),
  questionId: integer('question_id')
    .notNull()
    .references(() => question.id),
  selectedOptionId: integer('selected_option_id').references(() => option.id),
  isCorrect: boolean('is_correct').notNull().default(false),
  // How long the student spent on this question in milliseconds
  timeSpentMs: integer('time_spent_ms'),
  answeredAt: timestamp('answered_at').notNull().defaultNow(),
})

// ---------------------------------------------------------------------------
// Bookmark — saved questions per user
// ---------------------------------------------------------------------------

export const bookmark = pgTable('bookmark', {
  id: serial('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id),
  questionId: integer('question_id')
    .notNull()
    .references(() => question.id),
  createdAt: timestamp('created_at').notNull().defaultNow(),
}, (t) => [
  unique('bookmark_user_id_question_id_unique').on(t.userId, t.questionId),
])

// ---------------------------------------------------------------------------
// Relations — for Drizzle relational query API
// ---------------------------------------------------------------------------

export const subjectRelations = relations(subject, ({ many }) => ({
  topics: many(topic),
  questions: many(question),
  practiceSessions: many(practiceSession),
}))

export const examRelations = relations(exam, ({ many }) => ({
  questions: many(question),
  practiceSessions: many(practiceSession),
}))

export const topicRelations = relations(topic, ({ one, many }) => ({
  subject: one(subject, { fields: [topic.subjectId], references: [subject.id] }),
  questions: many(question),
}))

export const questionRelations = relations(question, ({ one, many }) => ({
  exam: one(exam, { fields: [question.examId], references: [exam.id] }),
  subject: one(subject, { fields: [question.subjectId], references: [subject.id] }),
  topic: one(topic, { fields: [question.topicId], references: [topic.id] }),
  options: many(option),
  sessionAnswers: many(sessionAnswer),
  bookmarks: many(bookmark),
}))

export const optionRelations = relations(option, ({ one }) => ({
  question: one(question, { fields: [option.questionId], references: [question.id] }),
}))

export const practiceSessionRelations = relations(practiceSession, ({ one, many }) => ({
  user: one(user, { fields: [practiceSession.userId], references: [user.id] }),
  exam: one(exam, { fields: [practiceSession.examId], references: [exam.id] }),
  subject: one(subject, { fields: [practiceSession.subjectId], references: [subject.id] }),
  answers: many(sessionAnswer),
}))

export const sessionAnswerRelations = relations(sessionAnswer, ({ one }) => ({
  session: one(practiceSession, { fields: [sessionAnswer.sessionId], references: [practiceSession.id] }),
  question: one(question, { fields: [sessionAnswer.questionId], references: [question.id] }),
  selectedOption: one(option, { fields: [sessionAnswer.selectedOptionId], references: [option.id] }),
}))

export const bookmarkRelations = relations(bookmark, ({ one }) => ({
  user: one(user, { fields: [bookmark.userId], references: [user.id] }),
  question: one(question, { fields: [bookmark.questionId], references: [question.id] }),
}))

export const userRelations = relations(user, ({ many }) => ({
  practiceSessions: many(practiceSession),
  bookmarks: many(bookmark),
}))
